### ISSUE TITLE
Extract event information from event bus and send to Slack

### ISSUE THREAD

**Issue by emetha** [emetha/Mr.SaltSlack#2]
Extract event information from the event bus:
https://docs.saltstack.com/en/getstarted/event/events.html

Salt Reactors:
https://docs.saltstack.com/en/latest/topics/reactor/

Events:
https://docs.saltstack.com/en/master/topics/event/events.html

**Comment by phwes** [comment]
Probably done this way:
Event -> React -> salt.runner.http + salt.runners.state

**Comment by emetha** [comment]
We want to watch for event (see type below)

We are using Event type - Job Event Return: 

salt/run/<JID>/ret
    Fired when a runner function returns
    Variables
            jid -- The job ID.
            fun -- The name of the runner function, with runner. prepended to it (e.g. runner.jobs.lookup_jid)
            fun_args -- The arguments passed to the runner function (e.g. ['20160829225914848058'])
            return -- The data returned by the runner function

**Comment by emetha** [comment]
Done.
